#Exception handling

# def upgrade():
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.create_table('lecturers',
#         sa.Column('id', sa.Integer(), nullable=False),
#         sa.Column('name', sa.String(length=50), nullable=True),
#         sa.Column('profession', sa.String(length=50), nullable=True),
#         sa.PrimaryKeyConstraint('id')
#     )
#     op.create_table('student_lesson',
#         sa.Column('student_id', sa.Integer(), nullable=False),
#         sa.Column('lesson_id', sa.Integer(), nullable=True),
#     )
#     op.create_table('students',
#         sa.Column('id', sa.Integer(), nullable=False),
#         sa.Column('name', sa.String(length=50), nullable=True),
#         sa.Column('unit', sa.String(length=50), nullable=True),
#         sa.PrimaryKeyConstraint('id')
#     )
#     op.create_table('lessons',
#         sa.Column('id', sa.Integer(), nullable=False),
#         sa.Column('title', sa.String(length=50), nullable=True),
#         sa.Column('location', sa.String(length=50), nullable=True),
#         sa.Column('time', sa.String(length=50), nullable=True),
#         sa.Column('lec_id', sa.Integer(), nullable=True),
#         sa.Column('student_id', sa.Integer(), nullable=True),
#         sa.ForeignKeyConstraint(['lec_id'], ['lecturers.id'], ),
#         sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
#         sa.PrimaryKeyConstraint('id')
#     )
#     # ### end Alembic commands ###


# def downgrade():
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.drop_table('lessons')
#     op.drop_table('students')
#     op.drop_table('lecturers')
#     # ### end Alembic commands ###
#     # ### end Alembic commands ###
